### ISSUE TITLE
fusionner les bouton "pause" et "resume"

### ISSUE THREAD

**Issue by leo-roggy** [polytopal/worlds-war#100]
Un seule bouton "pause/resume" ça serait pas plus logique ? Ça éviterait d'avoir 2 Action avec le même raccourcis mais seulement 1 activé a la fois.

**Comment by polytopal** [comment]
Oui, je trouverais aussi ça plus propre. Si jamais quelqu'un a envie de passer du temps là dessus... :p

**Comment by remdu** [comment]
C'est typiquement le truc de GUI sur lequel je pense qu'il faut pas qu'on perde du temps. J'aurais peut être pu le faire à la base mais là ça sert plus à rien, ça marche maintenant, ça marchera pas plus avec pause/resume button.

**Comment by polytopal** [comment]
Ona pas le temps osef
