### ISSUE TITLE
Implémenter le spawn de fourmis dans les fourmilières

### ISSUE THREAD

**Issue by leo-roggy** [polytopal/worlds-war#22]
La fourmilière fait spawn des fourmis a intervalle régulier et consomme de la bouffe a chaque fois. Rien ne spawn si il n'y a plus de bouffe dans la fourmilière.

**Comment by polytopal** [comment]
Il faut aussi implémenter le constructeur de AntBody dans cette tâche, et donc calculer les stats de la fourmi en fonction de sa breed et de sa caste.
