### ISSUE TITLE
créer la classe EnvObjectGrid (ou autre nom ...)

### ISSUE THREAD

**Issue by leo-roggy** [polytopal/worlds-war#48]
Cette classe contient un objet Grid<EnvObjectCell>, elle contient toutes les methodes qui permettent de voir et de modifier des objets sur les cellules (pour le moment ces methodes sont dans Environment Utils). S'inspirer de la classe PerceptionGrid
- ca serait bien d'encapsuler toutes les classes concernant les Perveivable dans un package, même chose pour celles concernant les envObject

**Comment by polytopal** [comment]
Ca serait pas plutot CellGrid ?
BTW les fcts que j'ai codees pourraient aussi etre au niveau de Cell... a discuter mais ya differentes manières viable d'organiser ce code

**Comment by leo-roggy** [comment]
Vouaip, faudra voir ca ensemble
