### ISSUE TITLE
Processus (swing ?) qui continue à tourner après l'arrêt de Janus

### ISSUE THREAD

**Issue by Goinf** [polytopal/worlds-war#62]
Pour reproduire le bug : 
- Lancer la Simulator.sarl
- Faire une nouvelle simu : le pop-up "New Simulation" apparait
- Fermer le pop-up (croix rouge/ALT+F4)
- Fermer la fenêtre principale (croix rouge/ALT+F4)
  -> le processus Java(TM) Platform SE Binary tourne toujours, même si "Tous les services du noyau ont été arrêtés"
  NB : si on close le pop-up "New Simulation" avec le bouton "Cancel" (fermeture normale), le processus disparait normalement

**Comment by leo-roggy** [comment]
A priori J'ai réglé le bug dans la branche gui-filter en mettant un "dispose on close" sur la pop-up. A verifier une fois que tout sera merge.

**Comment by leo-roggy** [comment]
Je suis allé checker, de base les JDialog sont sur "hide on close". Je comprends pas comment un truc aussi stupide peut être réglé par défaut ...

The value is set to HIDE_ON_CLOSE by default. Changes to the value of this property cause the firing of a property change event, with property name "defaultCloseOperation".

**Comment by Goinf** [comment]
Fixed and closed
