### ISSUE TITLE
Mettre la simulation en pause/modifier la vitesse de la simulation

### ISSUE THREAD

**Issue by polytopal** [polytopal/worlds-war#7]
Permettre de faire une pause dans la simulation/reprendre.
Ajouter la possibilité de simuler étape par étape
Permettre de changer la vitesse de simulation

**Comment by remdu** [comment]
Je peux m'en charger dans ma PR

**Comment by polytopal** [comment]
#33 a ajouté la gestion de la vitesse de la simulation, je vais créer une autre issue pour la pause
