### ISSUE TITLE
Bug de vitesse

### ISSUE THREAD

**Issue by leo-roggy** [polytopal/worlds-war#70]
Mon simulator fait des pointes à 500 steps/seconde en slow, je crois qu'il est en excès de vitesse ...
Plus on lance de nouvelle simulation plus la vitesse augment, comme si le scheduler de l'ancien environnement tournait toujours.

Bug apparu depuis le merge de la branche sur la pause à priori.

**Comment by leo-roggy** [comment]
Et la pause ne fonctionne plus

**Comment by polytopal** [comment]
ça a l'air de fonctionner plutot bien chez moi... T'arrives à le reproduire à 100% ?

**Comment by leo-roggy** [comment]
oui.
Essaie de spam le ctrl-n tu va voir

**Comment by polytopal** [comment]
Oui je confirme... Ca se produit quand la vitesse est suffisament faible et qu'on crée un environnement rapidement à première vue.

Faudra voir ce qu'on fait demain...

**Comment by leo-roggy** [comment]
![image](https://cloud.githubusercontent.com/assets/9866378/15482784/bcd5bf28-2131-11e6-9c37-b7ca642946eb.png)
nouveau record :)
