### ISSUE TITLE
Fourmis qui bloquent l'accès à la fourmilière

### ISSUE THREAD

**Issue by polytopal** [polytopal/worlds-war#75]
Le problème le plus récurrent et ennuyeux en ce moment c'est que nos fourmis se prennent un petit peu trop pour des syndicalistes français et bloquent l'accès à la fourmilière. Par contre c'est pas évident à corriger...

Solutions envisageables :
- Faire des fourmilières sur plusieurs cases -> relativement réaliste, mais compliqué à mettre en place
- Au niveau des operational behaviours, "forcer" une fourmi à tenter un déplacement qui fonctionne (quitte à aller dans la direction opposée à l'objectif) -> permet de s'assurer qu'au moins certaines fourmis sont toujours en mouvement, ça peut débloquer pas mal de situations. Nécessite un peu de réflexion pour mettre ça proprement sur tous les mouvements effectués dans operational behaviours, mais ça me semble raisonnable.
- Faire en sorte que les fourmis s'enterrent dans la fourmilière quand il y a trop de monde -> comment déterminer s'il y a trop de monde ? Si la fourmi qui veut sortir de la fourmilière ne peut pas, elle burrow jusqu'à ce que son mouvement lui semble possible ?
- Stopper les grêves grâce à l'état d'urgence, ainsi que des utilisations stratégiques et judicieuses de 49.3 -> nécessite d'implémenter les fourmis soldats d'abord. (ensuite on pourra en faire patrouiller de manière similaire à un chasse neige, ça déblaie bien le chemin).
- dès qu'une fourmilière utilise une influence move pour aller sur une fourmilière, l'environnement l'enterre automatiquement. Les fourmis dans les fourmilières peuvent être packées. Elle sont unburrow automatiquement quand elles sortent. Donc l'influence burrow ne servirait a rien. (credits to /u/leo for this idea)

Thoughts ? (ça veut dire "pensées" en anglais.)

**Comment by leo-roggy** [comment]
La réponse D

**Comment by leo-roggy** [comment]
Je pense que de forcer la fourmi a bouger ça serait pas mal.
Une solution pour coder ça ça serait :
Si la fourmi ne peut pas aller tout droit, elle choisit un sens de rotation aléatoirement (horaire ou anti-horaire) pour calculer la direction adjacente, tant que la nouvelle direction est bloquée, elle continue de tourner, jusqu’à avoir fait un tour complet.

**Comment by leo-roggy** [comment]
Une autre chose qu'il serait pas mal :
dès qu'une fourmilière utilise une influence move pour aller sur une fourmilière, l'environnement l'enterre automatiquement. Les fourmis dans les fourmilières peuvent être packées. Elle sont unburrow automatiquement quand elles sortent.
Donc l'influence burrow ne servirait a rien.

**Comment by Goinf** [comment]
Moi je propose d'envoyer des CRS pour débloquer les accès à la fourmilière bloquée par les fourmis CGT/SUD. C'est ce qui a été fait ce matin à la fourmilière pétrolière de Douchy-les-mines.
Sinon la solution de /u/leo est sympa, mais peut-être à nuancer. Le fonctionnement semble OK à première vue pour les gatherer, mais il sera peut-être embêtant pour les autres castes dans le turfu (need réfléchissement). 
En tout cas elle me semble plus mieux que la solution qui consisterait à tenter de bouger par tous les moyens, ce qui voudrait dire qu'à chaque step on aurait mass fourmis qui feraient 3/4 tests sur les cases adjacentes, avant de faire marche arrière (lent et pas très RP imo)

**Comment by polytopal** [comment]
Justement, à mon avis la solution 2 est assez RP puisque des fourmis qui se bloquent se mettent à tourner dans tous les sens pour trouver un passage.
Après, c'est vrai que sur un énorme gros tas ça pourrait poser des problèmes de perfs, mais pour l'instant on en a aucun donc est-ce que ça vaudrait pas le coup de tenter ?

**Comment by leo-roggy** [comment]
Le burrow dans les ant hill est codé et mergé.

**Comment by polytopal** [comment]
C'est plutot beau jeu actuellement, on pourra voir ce que ça donne à terme
