### ISSUE TITLE
Définition des paramètres de simulation

### ISSUE THREAD

**Issue by polytopal** [polytopal/worlds-war#8]
Menu qui permet de définir ces paramètres au lancement d'une nouvelle simulation
Lancer une nouvelle simulation au lancement du programme (afficher la fenêtre de nouvelle simulation)

**Comment by remdu** [comment]
J'ai déjà fais une partie de ça du coup. Pour les paramètres de simulation bah il faudra le faire quand on aura des choses à paramétrer

**Comment by polytopal** [comment]
On sait déjà ce qui est à paramétrer : largeur, hauteur, et une liste de 2 à N colonies de fourmis, avec le choix de la race pour chaque colonie.

**Comment by Goinf** [comment]
La nuit, c'est bien. Ya du zinternet. Je récupère les dernières màj et je m'occupe de cette issue demain matin.

**Comment by polytopal** [comment]
#30
