### ISSUE TITLE
Système d'unités

### ISSUE THREAD

**Issue by polytopal** [polytopal/worlds-war#85]
Pour l'instant, on n'a défini aucune unité, c'est pas beau jeu.

Il faudrait au moins définir : 
- Distance entre les cases (en mm, cm ?)
- Durée d'une step

Puis adapter l'affichage :
- [ ] Vitesse de simulation : passer de min, normal, fast à, par exemple, temps réel, x2, x5, x10, max
- [ ] Afficher le temps réel (h, min, sec) écoulé depuis le début de la simulation, au lieu du nombre de steps

**Comment by leo-roggy** [comment]
Proposition : 
1 case = 2 cm²
1 step = 1/4 s
vitesse normale = 4 step/s

=> fourmi 8 cm/s
=> map 300*300 = 2.4m²

**Comment by remdu** [comment]
Hmm je vois pas trop l'intérêt de rapporter ça à des unités réelles. On est clairement loin du réel en terme d'abstraction là

**Comment by polytopal** [comment]
Bah c'est un simulateur normalement, donc si on avait fait les choses bien, on aurait défini ça dès le début. Mais un simulateur doit fonctionner en unités réelles, sinon il n'a aucun intérêt. Donc pour le vendre, on doit rajouter un emballage marketing avec des unités.

Par contre, j'ai pas compris la partie "en terme d'abstraction" de ta phrase.

**Comment by polytopal** [comment]
Bah c'est un simulateur normalement, donc si on avait fait les choses bien, on aurait défini ça dès le début. Mais un simulateur doit fonctionner en unités réelles, sinon il n'a aucun intérêt. Donc pour le vendre, on doit rajouter un emballage marketing avec des unités.

Par contre, j'ai pas compris la partie "en terme d'abstraction" de ta phrase.

**Comment by remdu** [comment]
Bah je veux dire que notre simulateurr bah il est très symbolique, il a pas grand chose à voir avec la réalité à part le thème et la stigmergie. Du coup l'intérêt d'établir un rapport avec de vraies unités me semble carrément non existant. Je vois pas de quoi tu parles quand tu dis "vendre"  "emballage marketing" on le vends à personne ce simulateur, et les seules personnes qui vont le voir vont être de type technique. J'ai jamais entendu parler de loi ou de projet de loi interdisant les simulateurs qui n'utilisent pas d'unités réelles aussi.

**Comment by Goinf** [comment]
C'est le principe d'un simulateur d'être symbolique, tu ne peux pas recopier tous les aspects de la réalité avec un simulateur. Mais je suis d'accord pour rajouter du RP en traduisant nos unités "techniques" (steps, cases, ...) en unités réelles (cm, s). Si on n'avait que VI, ça ne serait pas indispensable, mais avec GL en plus c'est quasi-obligatoire imo. Et puis ça pourrait nous permettre de customiser notre simulateur avec des données sur des vrais races de fourmis. 
Puisque la MS de TOUTES les fourmis est fixée dans notre simulateur (1 case/step), on peut choisir une race en particulier pour étalonner notre système d'unités (exemple de MS ici http://www.acideformik.com/forums/index.php?showtopic=8491). En moyenne on peut partir sur du 4 ou 5 cm/s, donc petite modif de la prop de leo : 
- 1 case = 2cm² (=> fourmi.size<=1.4cm)
- 1 step = 1/2s
- normal speed = 2step/s
- => fourmi.speed = 4 cm/s

**Comment by remdu** [comment]
En effet un simulateur est symbolique, mais le notre en particulier est très très très loin de la réalité, comme je l'ai déjà expliqué. Depuis quand la GL52 demande d'utiliser des unités réelles? Si tu veux customiser le simulateur avec des données sur les vraies races des fourmis, faut aussi rajouter le nombre de pattes, rendre notre simulateur temps réel avec espace continu, utiliser les vraies données de concentration de phéromones et leur émission, faire des tests pour voir à quelle distance une fourmi est capable de reconnaître du sucre. Ajouter l'existence des reines et des larves....

**Comment by polytopal** [comment]
Je pars sur 2cm*2cm (4cm² bande de nuls en maths) et 2 steps = 1 secondes
