### ISSUE TITLE
Lier Simulator et GUI

### ISSUE THREAD

**Issue by polytopal** [polytopal/worlds-war#9]

**Comment by remdu** [comment]
Donc pour clarifier : je fais "git merge app-skeleton" après avoir pull la version actuelle? ensuite je lie les 2 bouts en remplaçant fake-gui et autre si besoin, puis je fais un git push? Je prends le train de 18h, je vais m'en occuper pendant le train je pense, puis un git push une fois chez moi

**Comment by polytopal** [comment]
Non, tu te mets juste sur ma branche, tu pull pour être à jour, puis de là tu crées ta propre branche. Elle partira de la mienne.
Ou alors tu crées une nouvelle branche depuis master et tu merge app-skeleton dessus. Par contre ne merge surtout rien sur master, et ne push que sur une branche à toi
