### ISSUE TITLE
Equilibrage : colonies meurent trop vite

### ISSUE THREAD

**Issue by remdu** [polytopal/worlds-war#90]
Les colonies de fourmis finissent par mourir alors qu'elles disposent encore de beaucoup de nourriture autour d'elles. Il faudrait équilibrer ça, genre avec un multiplicateur de la nourriture qu'elles gagnent ou bien en diminuant la nourriture qu'elles perdent.

**Comment by polytopal** [comment]
Oui.
Jusqu'à maintenant on n'a pas vraiment équilibré en fait.

Un des problèmes d'équilibrage est qu'une fourmilière snowball beaucoup : si elle a beaucoup de food à coté d'elle, elle va dès le début faire des gros stocks, et pouvoir survivre la dessus assez longtemps meme sans trouver de nourriture. Par contre une fourmilière un peu moins bien placée peut dépenser beaucoup de ses réserves initiales à produire des fourmis qui n'auront aucunes phéromones à suivre.

Je pense que ce qui pourrait être intéressant, sans faire de fourmilière trop intelligente serait que la fréquence à laquelle la fourmilière fait spawn une fourmi dépende de la quantité de nourriture qu'elle contient.

**Comment by remdu** [comment]
Non mais là c'est pas un problème de snowball du tout. Il y a des colonies avec énormement de food autour d'elles qui meurent.

**Comment by polytopal** [comment]
On dirait qu'il y a un bug quelque part parce que j'ai vu des fourmilières produire bien plus de fourmis que ce qu'elle est censée faire...
Donc faudra se pencher là dessus avant d'équilibrer
