### ISSUE TITLE
/!\ Enable Assertions (VM param) /!\

### ISSUE THREAD

**Issue by Goinf** [polytopal/worlds-war#91]
Impératif. Les assertions sont utilissées dans le code, mais pas prises en compte au niveau de la VM si non précisé.
Pour éviter qu'elles soient ignorées : 
- sur eclipse-sarl, aller dans Run > Run configurations...
- choisir la run config du projet (Simulator)
- dans l'onglet "Arguments", aller dans la 3ème zone de texte (arguments for the JVM) et rajouter "-ea"
- recompiler et crier ALED psk la dernière PR plante.

**Comment by polytopal** [comment]
hé ho elle plante plus ma pr d'abord.

**Comment by Goinf** [comment]
OK, tout le monde a visu, on ferme.
