### ISSUE TITLE
pheromone spread

### ISSUE THREAD

**Issue by remdu** [polytopal/worlds-war#96]
J'ai fait des tests en local avec le spread de phéromone, Je pense que ça serait assez intéressant niveau convergence etc. Le problème principal c'est qu'il faut permettre aux envCells de connaître leur position pour simplifier, et il faudrait également qu'elles aient une arrayList de leurs voisins pour éviter de les calculer des millions de fois par frame... J'ai essayé ça fait ramer

**Comment by polytopal** [comment]
J'ai déjà pensé à une implémentation, mais à priori pas besoin de toucher à EnvCell (tout se fait dans EntUtils, on pourra en discuter).

Ca pourra se tenter.

**Comment by Goinf** [comment]
Est-ce qu'on en a vraiment besoin ? Je trouve que le comportement actuel est pas dégueu en terme de pathfinding. A condition que bcp d'agents suivent le même chemin, ce qui est le principe de la colonie de fourmis

**Comment by polytopal** [comment]
Je pense pas non plus qu'on en ait besoin, mais si quelqu'un s'ennuie et veut tenter je n'ai rien contre

**Comment by polytopal** [comment]
On a pas le temps osef
